### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by sm354** [belindal/state-probes#2]
Hi! Could you please share the definitions of `state_keys` and `tgt_state_keys` variables [here](https://github.com/belindal/state-probes/blob/1685a7167513a8348b127729732e6ea5c09e404a/data/textworld/tw_dataloader.py#L403)? Any description of the `else` condition and of the task being achieved in this condition would also really help.

**Comment by belindal** [comment]
Hi Shubham, looks like these should be `self.state_keys` and `self.tgt_state_keys`. Thanks for catching! (Looks to be some old code I ported over from elsewhere that doesn't actually get used). This if-else statement specifies whether or not to return state annotations, and which state annotation (specified by `state_key`) to return. `tgt_state_key` specifies whether the target we're decoding is the final state or the initial state.
