### ISSUE TITLE
Minor bug report

### ISSUE THREAD

**Issue by ajyl** [belindal/state-probes#3]
Hello! I really enjoyed your paper. Just a minor question:
https://github.com/belindal/state-probes/blob/0fa663ff66ae5919889664c75560d21d4644f675/scripts/probe_alchemy.py#L178
Should this line say `"single_beaker_init in args.probe_target or "single_beaker_final" in args.probe_target`? Otherwise this line will always compute to True?

**Comment by belindal** [comment]
Hi! Thanks for pointing this out! I've fixed it now.
